info:
  description: A glimpse into your awesome API
  title: API badc38f2-400f-4723-9c38-f2400fc72308
  version: 1.0.0
openapi: 3.0.3
paths:
  /pet:
    post:
      description: This endpoint allows the user to create a new pet by sending a
        JSON array in the request body. The response will contain a status code of
        200 if the creation was successful. This endpoint falls under the 'pet' tag.
      requestBody:
        content:
          application/json:
            schema:
              items: {}
              nullable: false
              type: array
      responses:
        '200':
          content:
            application/json:
              schema:
                items: {}
                nullable: false
                type: array
          description: OK
      summary: Create a new pet.
      tags:
      - pet
  /pet/findByTags:
    get:
      description: This endpoint retrieves a list of pets that have been tagged with
        the specified keywords. It allows searching for multiple tags at once by separating
        them with a comma. If no tags are specified, it returns all pets.
      parameters:
      - in: query
        name: tags
        required: false
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                items: {}
                nullable: false
                type: array
          description: OK
      summary: Find pets by tags
      tags:
      - pet
  /pet/{pet}:
    get:
      description: This endpoint allows users to retrieve information about a specific
        pet by providing the pet ID as a parameter in the path. The response will
        contain an array with detailed information about the pet.
      parameters:
      - in: path
        name: pet
        required: true
        schema:
          type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                items: {}
                nullable: false
                type: array
          description: OK
      summary: Retrieve information about a specific pet.
      tags:
      - pet
servers:
- url: https://petstore3.swagger.io/api/v3
