info:
  description: A glimpse into your awesome API
  title: API badc38f2-400f-4723-9c38-f2400fc72308
  version: 1.0.0
openapi: 3.0.3
paths:
  /pet:
    post:
      description: This endpoint allows you to add a new pet to the store by providing
        a JSON object in the request body, and returns a success message with a JSON
        array of the added pet's details. This endpoint is tagged as 'pet'.
      requestBody:
        content:
          application/json:
            schema:
              items: {}
              nullable: false
              type: array
      responses:
        '200':
          content:
            application/json:
              schema:
                items: {}
                nullable: false
                type: array
          description: OK
      summary: Add a new pet to the store.
      tags:
      - pet
    put:
      description: This endpoint allows you to update a pet's information by sending
        a JSON array in the request body. The response will be a JSON array indicating
        that the update was successful. The endpoint is tagged as 'pet'.
      requestBody:
        content:
          application/json:
            schema:
              items: {}
              nullable: false
              type: array
      responses:
        '200':
          content:
            application/json:
              schema:
                items: {}
                nullable: false
                type: array
          description: OK
      summary: Update a pet.
      tags:
      - pet
  /pet/findByStatus:
    get:
      description: This endpoint retrieves a list of pets based on the provided status
        query parameter. The response is an array of pet objects.
      parameters:
      - in: query
        name: status
        required: false
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                items: {}
                nullable: false
                type: array
          description: OK
      summary: Find pets by status
      tags:
      - pet
  /pet/{pet}:
    get:
      description: This endpoint retrieves an array of pets based on their ID number
        passed in the path parameter. The response will contain a list of pets represented
        in a JSON format.
      parameters:
      - in: path
        name: pet
        required: true
        schema:
          type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                items: {}
                nullable: false
                type: array
          description: OK
      summary: Get a list of pets by ID.
      tags:
      - pet
  /store/{store}:
    post:
      description: This endpoint creates a new record in the specified store using
        the provided JSON array as the request body and returns the same array as
        the response body if successful. The store name is provided as a required
        parameter in the path.
      parameters:
      - in: path
        name: store
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              items: {}
              nullable: false
              type: array
      responses:
        '200':
          content:
            application/json:
              schema:
                items: {}
                nullable: false
                type: array
          description: OK
      summary: Create a new record in the specified store.
      tags:
      - store
servers:
- url: https://petstore3.swagger.io/api/v3
