info:
  description: A glimpse into your awesome API
  title: API badc38f2-400f-4723-9c38-f2400fc72308
  version: 1.0.0
servers:
- url: https://petstore3.swagger.io/api/v3
paths:
  /pet/findByTags:
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                items: {}
                nullable: false
                type: array
      tags:
      - pet
      parameters:
      - in: query
        name: tags
        required: false
        schema:
          type: string
  /pet/{pet}:
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                items: {}
                nullable: false
                type: array
      tags:
      - pet
      parameters:
      - in: path
        required: true
        name: pet
        schema:
          type: integer
  /pet:
    post:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                items: {}
                nullable: false
                type: array
      tags:
      - pet
      requestBody:
        content:
          application/json:
            schema:
              items: {}
              nullable: false
              type: array
openapi: 3.0.3
