info:
  description: A glimpse into your awesome API
  title: API badc38f2-400f-4723-9c38-f2400fc72308
  version: 1.0.0
openapi: 3.0.3
paths:
  /pet:
    post:
      description: This endpoint allows the user to add a new pet to the store by
        sending a JSON array in the request body. The response will be a 200 status
        code with a JSON array indicating that the operation was successful.
      requestBody:
        content:
          application/json:
            schema:
              items: {}
              nullable: false
              type: array
      responses:
        '200':
          content:
            application/json:
              schema:
                items: {}
                nullable: false
                type: array
          description: OK
      summary: Add a new pet to the store.
      tags:
      - pet
  /pet/findByTags:
    get:
      description: This endpoint allows searching for pets that have been tagged with
        specific keywords. Returns an array of pet objects matching the specified
        tags.
      parameters:
      - in: query
        name: tags
        required: false
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                items: {}
                nullable: false
                type: array
          description: OK
      summary: Find pets by tags
      tags:
      - pet
  /pet/{pet}:
    get:
      description: This endpoint retrieves a specific pet by ID from the server. It
        requires an integer value for the pet ID in the path parameter and returns
        an array of pet objects in JSON format if the ID is found in the server's
        database.
      parameters:
      - in: path
        name: pet
        required: true
        schema:
          type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                items: {}
                nullable: false
                type: array
          description: OK
      summary: Get pet by ID
      tags:
      - pet
servers:
- url: https://petstore3.swagger.io/api/v3
